comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false # カバレッジの変更時のみコメントを表示する
  require_base: true # [true :: must have a base report to post]
  require_head: true # [true :: must have a head report to post]
  hide_project_coverage: false
