version: "3.8"
services:
  localstack:
    hostname: dust_localstack
    container_name: localstack
    image: localstack/localstack
    ports:
      - 4566:4566 # LocalStack Gateway
      # - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=dynamodb,s3,sqs
      - DEFAULT_REGION=ap-northeast-1
      # - DEBUG=${DEBUG-}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    tty: true
  mysql:
    image: mysql:8.0.34
    container_name: mysql
    # ホスト名を明示的に指定する
    hostname: dust_mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #実行時のコマンド
    ports:
      - "3306:3306" #ポート指定、ホスト:コンテナ
    environment: #コンテナ内の環境変数を指定
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dust
      MYSQL_USER: dust
      MYSQL_PASSWORD: test
      TZ: "Asia/Tokyo"
    # volumes:
    # - ./db/mysql/.db_data/:/var/lib/mysql/
    # - ./db/dumps/:/dumps/
    #- ./db/log/mysql/:/var/log/mysql/
    tty: true
