name: ci
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.yml"
      - "**.go"
  workflow_dispatch:
permissions: write-all

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      # 差分を取得
      - name: Get changed files
        id: get_changed_files
        run: |
          files=$(git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }} | tr '\n' ' ')
          echo "changed files: $files"
          echo "CHANGED_FILES=$files" >> $GITHUB_OUTPUT
      # Goファイルが変更されているかチェック
      - name: Check go files changed
        id: check_go_files_changed
        run: |
          GO_FILES_CHANGED=false
          for file in ${{ steps.get_changed_files.outputs.CHANGED_FILES }}; do
            if [[ "$file" == *.go || "$file" == go.mod || "$file" == go.sum ]]; then
              echo "GO_FILES_CHANGED=true" >> $GITHUB_OUTPUT
              break
            fi
          done
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Check lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          golangci_lint_flags: "--config=.golangci.yml"
      - name: Check vulnerability
        run: make vuln
        shell: bash
      # ビルド
      - name: Build
        run: make build
        shell: bash
      # テスト実行
      - name: Run Tests
        run: make ci-test
      - name: create report
        uses: k1LoW/octocov-action@v1
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
