name: go-test
on:
  push:
    branches:
      - main
    paths:
      - "**.go"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.go"
  workflow_dispatch:
permissions: write-all

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Lint
        run: make lint
        shell: bash
      - name: Vulnerability Assessment
        run: make vulncheck
        shell: bash
      # ビルド
      - name: Build
        run: make build
        shell: bash
      # テスト実行
      - name: Tests
        run: make ci-test
        shell: bash
      - name: create report
        uses: k1LoW/octocov-action@v1
